apiVersion: v1
kind: Secret
metadata:
  name: {{ include "singlestore-helm.fullname" . }}-secret
type: Opaque
stringData:
  license: {{ required "A valid license is required" .Values.spec.license | quote }}
  adminHashedPassword: {{ required "spec.adminHashedPassword is required" .Values.spec.adminHashedPassword | quote }}
