apiVersion: v2
name: singlestore-helm
description: A Helm chart for deploying SingleStore
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: SingleStore
    url: https://www.singlestore.com/
home: https://www.singlestore.com/
sources:
  - https://github.com/singlestore
keywords:
  - singlestore
  - memsql
  - database
  - kubernetes
  - helm
icon: https://www.singlestore.com/favicon.ico 